package model;
// Generated 27/01/2021 05:03:47 PM by Hibernate Tools 4.3.1



/**
 * DetalleId generated by hbm2java
 */
public class DetalleId  implements java.io.Serializable {


     private long numDetalle;
     private long idFactura;

    public DetalleId() {
    }

    public DetalleId(long numDetalle, long idFactura) {
       this.numDetalle = numDetalle;
       this.idFactura = idFactura;
    }
   
    public long getNumDetalle() {
        return this.numDetalle;
    }
    
    public void setNumDetalle(long numDetalle) {
        this.numDetalle = numDetalle;
    }
    public long getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(long idFactura) {
        this.idFactura = idFactura;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleId) ) return false;
		 DetalleId castOther = ( DetalleId ) other; 
         
		 return (this.getNumDetalle()==castOther.getNumDetalle())
 && (this.getIdFactura()==castOther.getIdFactura());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNumDetalle();
         result = 37 * result + (int) this.getIdFactura();
         return result;
   }   


}


