package model;
// Generated 27/01/2021 05:03:47 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detalle generated by hbm2java
 */
public class Detalle  implements java.io.Serializable {


     private DetalleId id;
     private Factura factura;
     private Producto producto;
     private BigDecimal precio;
     private long cantidad;

    public Detalle() {
    }

    public Detalle(DetalleId id, Factura factura, Producto producto, BigDecimal precio, long cantidad) {
       this.id = id;
       this.factura = factura;
       this.producto = producto;
       this.precio = precio;
       this.cantidad = cantidad;
    }
   
    public DetalleId getId() {
        return this.id;
    }
    
    public void setId(DetalleId id) {
        this.id = id;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public long getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(long cantidad) {
        this.cantidad = cantidad;
    }




}


