package model;
// Generated 27/01/2021 05:03:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private long numFactura;
     private Cliente cliente;
     private Date fecha;
     private Set detalles = new HashSet(0);

    public Factura() {
    }

	
    public Factura(long numFactura, Cliente cliente, Date fecha) {
        this.numFactura = numFactura;
        this.cliente = cliente;
        this.fecha = fecha;
    }
    public Factura(long numFactura, Cliente cliente, Date fecha, Set detalles) {
       this.numFactura = numFactura;
       this.cliente = cliente;
       this.fecha = fecha;
       this.detalles = detalles;
    }
   
    public long getNumFactura() {
        return this.numFactura;
    }
    
    public void setNumFactura(long numFactura) {
        this.numFactura = numFactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }




}


