package model;
// Generated 27/01/2021 05:03:47 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private long idProducto;
     private String nombre;
     private BigDecimal precio;
     private long stock;
     private Set detalles = new HashSet(0);

    public Producto() {
    }

	
    public Producto(long idProducto, String nombre, BigDecimal precio, long stock) {
        this.idProducto = idProducto;
        this.nombre = nombre;
        this.precio = precio;
        this.stock = stock;
    }
    public Producto(long idProducto, String nombre, BigDecimal precio, long stock, Set detalles) {
       this.idProducto = idProducto;
       this.nombre = nombre;
       this.precio = precio;
       this.stock = stock;
       this.detalles = detalles;
    }
   
    public long getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(long idProducto) {
        this.idProducto = idProducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public long getStock() {
        return this.stock;
    }
    
    public void setStock(long stock) {
        this.stock = stock;
    }
    public Set getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }




}


